### ISSUE TITLE
Prolems decopiling this on linux (sorry for my bad english)

### ISSUE THREAD

**Issue by Martin3245** [KiaraGale/Sonic-Mania-Addendum#13]
i tried to build this for linux but when i tried for start it crashed.

**Comment by KiaraGale** [comment]
The publicly available source code for Sonic Mania Addendum does not function on the latest builds of RSDKv5.
Only thing you can do is either use an older version of RSDKv5, or download the in-dev version of the mod in my modding thread found in the Retro Engine Modding Server on Discord.

**Comment by Martin3245** [comment]
the version in-dev here (in github) is outdated?

**Comment by KiaraGale** [comment]
This repository holds the source code for publicly available release builds for the mod, that being the SHC version.
I have a separate but private repository which hosts the source code + assets for the in-dev version that me and the dev team are currently working on.

**Comment by Martin3245** [comment]
oohhh, yeah i understand, thanks for ur help :)
