### ISSUE TITLE
Feature: Partner Ray Ability - Hang Glider + Small Music Edit

### ISSUE THREAD

**Issue by DolphinCube** [KiaraGale/Sonic-Mania-Addendum#14]
now know this mod didn't really recieve any updates for a while but I WOULD like to touch on something that would be cool to implement. When having ray as your partner. He can be used as a [glider just like this Sonic 3 A.I.R mod here](https://sonic3air.boards.net/thread/30/new-update-extra-slot-ray). Which would be a pretty neat feature.

Also. Can you possibly make an edit so the Act 1 Clear theme is the 3K Victory Theme while the un-used Mania Victory Theme is used for Act 2. I think that'll be a neat idea

**Comment by KiaraGale** [comment]
This is for bug/crash reports, not feature requests.
